### ISSUE TITLE
Architecture questions

### ISSUE THREAD

**Issue by nesnes** [Siviuze/KickCAT#5]
I really like how simple the current source code is, congrats!

The Bus class is starting to grow in size and could become difficult to maintain.

Should functions like `waitForMessage`, `getCurrentState`, `readMappedPDO`, `read/writeSDO`  be moved to the Slave class? Slaves would be listed in the bus and initialized with a shared pointer (or whatever) to the bus.

Other possibilities would be to move some of the Frames (datagrams) and Eeprom (read/fetch/ready) logic to dedicated classes.

**Comment by Siviuze** [comment]
Well, I would like to avoid cross referencing between bus and slaves so the only logic that can be moved shall not depends on bus access (like SII parsing or async message logic).

About frame logic, it is already handled in its own dedicated class?
Part of the eeprom logic could be moved to a dedicated class but we have to be careful to not increase the complexity. 

At a short and fast solution, I plan to move implementation of some sections (like eeprom logic) in a dedicated file but keeping it attached to Bus class. I feel that the Bus class is almost finished and that it shouldn't grow a lot more: almost all the remaining functionalities are attached to another layer (like mailbox for FoE or Frame for redundancy).
